# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SyGqv-zkh57u3WlnXu_fCmXExuNyMnvu
"""

import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

def model():
    df = pd.read_excel('day.xlsx')
    df.head()

    df.isnull().sum().sum()

    df.info()

    df.drop(['instant','dteday','casual','registered'],axis=1,inplace=True)

    df.head()

    df.shape

    X= df.drop('cnt',axis=1)
    y= df['cnt']

    y.shape

    cat_vars = ['season','yr','mnth','holiday','workingday','weathersit']
    num_vars = ['temp','atemp','hum','windspeed']

    from sklearn.compose import ColumnTransformer
    from sklearn.preprocessing import OneHotEncoder,StandardScaler

    numeric_transformer = StandardScaler()
    categorical_transformer = OneHotEncoder(drop='first',handle_unknown='ignore')
    ct = ColumnTransformer(
        transformers=
        [('cat',categorical_transformer,cat_vars),
        ('num',StandardScaler(),num_vars)],remainder='passthrough'
    )

    from sklearn.pipeline import Pipeline
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

    pipeline = Pipeline([('ct',ct),
                        ('model',LinearRegression())])

    from sklearn.model_selection import train_test_split
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

    pipeline.fit(X_train,y_train)

    y_pred = pipeline.predict(X_test)

    X_add= df[cat_vars+num_vars]

    ct.fit(X_add)

    MAE= mean_absolute_error(y_test,y_pred)
    MSE= mean_squared_error(y_test,y_pred)
    RMSE= np.sqrt(MSE)
    R2= r2_score(y_test,y_pred)

    print(f"MAE : {MAE}, MSE : {MSE}, RMSE : {RMSE}, R2 : {R2}")

    import joblib

    joblib.dump(pipeline, 'model.pkl')

if __name__ == "__main__":
    model()